# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fc4784afc25d47e0ed81dadf1e45301691557b3c2d29117d13465f52f6df975fa969e1c7e2dd95162ab539040fd03994141ef917e96b0cf29db0cd63d9b877

test:
  secret_key_base: 457ce1b455a33a376bcaa702b6c61652ac73dd0e47b7d5524c282e0496b637551857ef130c230286607494bede7c6400ce4c36bf53bec79370cd4e02febb77a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
